/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ErrorSpotterRouteImport } from './routes/error-spotter'
import { Route as IndexRouteImport } from './routes/index'

const ErrorSpotterRoute = ErrorSpotterRouteImport.update({
  id: '/error-spotter',
  path: '/error-spotter',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/error-spotter': typeof ErrorSpotterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/error-spotter': typeof ErrorSpotterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/error-spotter': typeof ErrorSpotterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/error-spotter'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/error-spotter'
  id: '__root__' | '/' | '/error-spotter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ErrorSpotterRoute: typeof ErrorSpotterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/error-spotter': {
      id: '/error-spotter'
      path: '/error-spotter'
      fullPath: '/error-spotter'
      preLoaderRoute: typeof ErrorSpotterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ErrorSpotterRoute: ErrorSpotterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
